spring.application.name=code-edtior-autocompleter
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=${GEMINI_MODEL:gemini-2.5-flash}
logging.level.com.griddynamics.codeedtior.autocompleter=DEBUG
